version: "3"
services:
  web:
    build: .
    depends_on:
      - mysql
      - adminer
      - mailhog
    ports:
      - "9080:80"
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: adminer:4.8.1
    ports:
      - "9081:8080"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "9082:8025"
